#!/usr/bin/env python3

import os
import subprocess

ZULIP_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "../../")
OUT_PATH = os.path.join(ZULIP_PATH, "static", "generated", "starlight_help")

subprocess.check_call(
    ["./tools/build-help-center", "--out-dir", OUT_PATH, "--no-relative-links"],
)
