# Generated by Django 5.0.9 on 2024-12-17 05:55

from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps


def set_default_value_for_can_add_subscribers_group(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    Realm = apps.get_model("zerver", "Realm")
    Stream = apps.get_model("zerver", "stream")
    NamedUserGroup = apps.get_model("zerver", "NamedUserGroup")

    for realm in Realm.objects.all():
        group = NamedUserGroup.objects.filter(
            name="role:nobody", realm=realm, is_system_group=True
        ).values("pk")
        Stream.objects.filter(realm=realm).update(can_add_subscribers_group=group)


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("zerver", "0653_stream_can_add_subscribers_group"),
    ]

    operations = [
        migrations.RunPython(
            set_default_value_for_can_add_subscribers_group,
            elidable=True,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
